openapi: 3.1.0
info:
  title: backoffice-bff-java-repository
  description: Api and Models
  version: v0.6.0
servers:
- url: https://api-emd.dev.cstar.pagopa.it/emd/backoffice
  description: Generated server url
  x-internal: true
paths:
  '/api/v1/tpp':
    post:
      tags:
      - tpp-controller-impl-v-1
      operationId: saveTpp
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TppDTOV1"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
    get:
      tags:
      - tpp-controller-impl-v-1
      operationId: getTppByEntityId
      summary: Retrieve TPP details by entityId extracted from token
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TppResponseDTOV1"
        "401":
          description: Unauthorized
        "404":
          description: Not Found
    patch:
      tags:
      - tpp-controller-impl-v-1
      operationId: patchTpp
      summary: Partially update TPP using entityId extracted from token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TppPatchDTOV1"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TppResponseDTOV1"
        "401":
          description: Unauthorized
        "404":
          description: Not Found
  '/api/v1/tpp/credentials':
    get:
      tags:
      - tpp-controller-impl-v-1
      operationId: getTppCredentials
      summary: Retrieve TPP credentials using entityId extracted from token
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
        "401":
          description: Unauthorized
        "404":
          description: Not Found
    put:
      tags:
      - tpp-controller-impl-v-1
      operationId: updateTppCredentials
      summary: Update TPP credentials using entityId extracted from token
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
        "401":
          description: Unauthorized
        "404":
          description: Not Found
  '/api/v1/tpp/credentials/pagopa':
    get:
      tags:
      - tpp-controller-impl-v-1
      operationId: getTppCredentialsPagopa
      summary: Retrieve TPP PagoPA credentials using entityId extracted from token
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
        "401":
          description: Unauthorized
        "404":
          description: Not Found
  '/api/v1/auth/exchange':
    post:
      tags:
      - backoffice-controller-impl
      operationId: getToken
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseDTO"
components:
  schemas:
    AgentLinkV1:
      type: object
      properties:
        fallBackLink:
          type: string
        versions:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/VersionDetailsV1"
    AuthenticationTypeV1:
      type: string
      enum:
      - OAUTH2
    ContactV1:
      type: object
      properties:
        name:
          type: string
        number:
          type: string
          pattern: "^\\d{9,10}$"
        email:
          type: string
          format: email
    TokenSectionV1:
      type: object
      properties:
        contentType:
          type: string
        pathAdditionalProperties:
          type: object
          additionalProperties:
            type: string
        bodyAdditionalProperties:
          type: object
          additionalProperties:
            type: string
    TppDTOV1:
      type: object
      properties:
        businessName:
          type: string
          minLength: 1
        messageUrl:
          type: string
          pattern: "^(https?|ftp)://[^ /$.?#].[^ ]*$"
        authenticationUrl:
          type: string
          pattern: "^(https?|ftp)://[^ /$.?#].[^ ]*$"
        authenticationType:
          $ref: "#/components/schemas/AuthenticationTypeV1"
        contact:
          $ref: "#/components/schemas/ContactV1"
        tokenSection:
          $ref: "#/components/schemas/TokenSectionV1"
        pspDenomination:
          type: string
        agentLinks:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/AgentLinkV1"
      required:
      - agentLinks
      - authenticationType
      - businessName
    TppResponseDTOV1:
      type: object
      properties:
        tppId:
          type: string
        businessName:
          type: string
          minLength: 1
        messageUrl:
          type: string
          pattern: "^(https?|ftp)://[^ /$.?#].[^ ]*$"
        authenticationUrl:
          type: string
          pattern: "^(https?|ftp)://[^ /$.?#].[^ ]*$"
        authenticationType:
          $ref: "#/components/schemas/AuthenticationTypeV1"
        contact:
          $ref: "#/components/schemas/ContactV1"
        tokenSection:
          $ref: "#/components/schemas/TokenSectionV1"
        pspDenomination:
          type: string
        agentLinks:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/AgentLinkV1"
      required:
      - agentLinks
      - authenticationType
      - businessName
    VersionDetailsV1:
      type: object
      properties:
        link:
          type: string
    TppPatchDTOV1:
      type: object
      properties:
        businessName:
          type: string
          minLength: 1
        messageUrl:
          type: string
          pattern: "^(https?|ftp)://[^ /$.?#].[^ ]*$"
        authenticationUrl:
          type: string
          pattern: "^(https?|ftp)://[^ /$.?#].[^ ]*$"
        authenticationType:
          $ref: "#/components/schemas/AuthenticationTypeV1"
        contact:
          $ref: "#/components/schemas/ContactV1"
        pspDenomination:
          type: string
        agentLinks:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/AgentLinkV1"
    ResponseDTO:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        token:
          type: string
