openapi: 3.1.0
info:
  title: backoffice-bff-java-repository
  description: Api and Models
  version: 0.1.0
servers:
- url: https://api-emd.dev.cstar.pagopa.it/emd/backoffice
  description: Generated server url
  x-internal: true
paths:
  '/api/auth/pagopa':
    post:
      tags:
      - backoffice-controller-impl
      operationId: getToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseDTO"
components:
  schemas:
    RequestDTO:
      type: object
      properties:
        token:
          type: string
    ResponseDTO:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        token:
          type: string
